import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sasha Blog",
  description: "Generated by create next app",
};

const header = (
  <header>
    <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
      <Image
        className="mx-auto pb-4"
        src="/logo.png"
        width={40}
        height={40}
        alt="logo"
      ></Image>
      <Link href="/">
        {" "}
        <h1 className="text-3xl text-white font-bold">Sasha's Blog Header</h1>
        <p className="text-slate-300">Subheading just for fun</p>
      </Link>
    </div>
  </header>
);

const footer = (
  <footer>
    <div className="border-t border-slate-500 mt-6 py-6 text-center text-slate-400">
      <h1>Sasha's Blog Footer</h1>
    </div>
  </footer>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
